name: Build & Deploy Spring Boot Backend to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch: # Permitir ejecución manual desde GitHub Actions

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests with embedded MongoDB
        run: mvn clean test -Dspring.profiles.active=test

      - name: Build with Maven for production
        run: mvn package -DskipTests -Dspring.profiles.active=prod

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: product-inventory
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.jar
